### ISSUE TITLE
Reverse-Toonification 

### ISSUE THREAD

**Issue by Andre1998Shuvam** [eladrich/pixel2style2pixel#138]
Hello! Can you please guide me on how to accomplish Reverse-Toonification process using your pSp encoder model? For example, converting toon faces to real ones or portraits to photographs.

**Comment by yuval-alaluf** [comment]
Hi @Andre1998Shuvam 
Is there a specific part of the process that you did not understand? If you pinpoint what you didn't understand it will assist me in helping you.

**Comment by Andre1998Shuvam** [comment]
Hello! I want to achieve this:

![image](https://user-images.githubusercontent.com/49407884/118087967-fe47d280-b3e3-11eb-9277-f4300beeee43.png)

Can you tell me how this can be done? 

I came across this image on a website. You can find this one and some other similar images in the link below:

http://www.nathanshipley.com/gan/#gan-016-reverse-toonification

In the website, it is mentioned that this work is based on your pSp encoder model. However, I cannot figure out how to proceed. I tried contacting Nathan Shipley several times but in vain. It will be very helpful if you can guide me on this.

**Comment by yuval-alaluf** [comment]
To the best of my knowledge, Nathan simply passed the images through the pretrained pSp encoder for inversion and did some post editing on the results. 
There is no training needed.

**Comment by Andre1998Shuvam** [comment]
Oh, okay! Thank you for the info. Can you tell me any other feasible approach to accomplish this?

**Comment by yuval-alaluf** [comment]
Regarding your questions at the end, I dont think that doing so will give you what you want since this will harm your reconstruction. 
If you wish to change the tone or color scheme of the output, you can try performing style mixing with an image whose color scheme you want transfer to the image of the Mona Lisa. You may consider this as a form of post processing, but it may give you what you are looking for.
