### ISSUE TITLE
Background preservation

### ISSUE THREAD

**Issue by duongquangvinh** [eladrich/pixel2style2pixel#165]
Hi sir!

I do not know that if I want to preserve background, which loss should I increase/decrease in training frontalization?

**Comment by yuval-alaluf** [comment]
There is no loss that explicitly preserves background. 
For the losses in frontalization we mainly decreased the L2 and LPIPS losses in order to change the pose of the individual. But a side effect of this was decreasing the background preservation. 
In my opinion, as is  it will be difficult to preserve both the background and change the pose.
