### ISSUE TITLE
about the pSpGAN's encoder

### ISSUE THREAD

**Issue by zbw0329** [eladrich/pixel2style2pixel#176]
Hi,Thanks for your excellent pSpGAN.
And I  have trained the encoder on CelebA dataset.
The before and after images don't look much alike.Shouldn't they look the same?

![OH I%`66 0@VMY$AEZ3G246](https://user-images.githubusercontent.com/50667397/126924688-db6ae340-453e-4c49-977e-1ac3425ed88f.png)

And some features disappeared, such as hands, which disappeared after the transformation.
What should I do if I want the pictures before and after encoding to be exactly the same?

**Comment by zbw0329** [comment]
And I want to know the value range of each loss.

**Comment by yuval-alaluf** [comment]
Your results are pretty good. You won't really be able to get a perfect reconstruction (maybe with optimization you'll get pretty close reconstructions but that'll take you a few minutes per image). 
Regarding the hands, StyleGAN doesn't really know how to generate images with hands which is why you are not able to reconstruct the hands. 

Regarding the loss, please see the detailed README or the paper.

**Comment by zbw0329** [comment]
Thanks for your reply.
