### ISSUE TITLE
Convert models to CoreML or ONNX?

### ISSUE THREAD

**Issue by melMass** [eladrich/pixel2style2pixel#177]
Hi,

Thanks for pSp, very cool project!!
I want to convert a model I have trained based on the `psp_celebs_sketch_to_face` to [CoreML](https://developer.apple.com/documentation/coreml) or [ONNX](https://onnx.ai/). I've seen #72 but it was closed by the OP.

### Is `pSp` jit compliant?

- when I try to `jit.load` the pt file directly I have the following error:
  `PytorchStreamReader failed reading zip archive: failed finding central directory`
- if I `jit.save` the pSp instance (`net` in the colab) I get the same error as in #72. 
    
    

  
  ```ruby
  RuntimeError: 
  Could not export Python function call 'FusedLeakyReLUFunction'. Remove calls to. 
  Python functions before export. Did you forget to add @script or @script_method 
  annotation? If this is a nn.ModuleList, add it to __constants__:
  ```

**Comment by yuval-alaluf** [comment]
We're not too familiar with ONNX and CoreML and it seems like the issue is indeed related to the CUDA extensions with the FusedLeakyReLU. One possible option is to use a native implementation of these classes instead of the official CUDA versions.
I believe rosinality added native support for the two CUDA kernels so you could try using his updated versions instead of the ones we have here: 
https://github.com/rosinality/stylegan2-pytorch/tree/master/op
I hope this can help a bit

**Comment by melMass** [comment]
> rosinality added native support for the two CUDA kernels so you could try using his updated versions

Thanks, I will experiment with it this week and report how it went here!

**Comment by vazkir** [comment]
Hi @melMass 

I am also looking into covering this model to ONNX, and I was wondering if you manage to get it to work? Would love to know how you achieved it!

**Comment by zeta7337** [comment]
> Hi @melMass
> 
> I am also looking into covering this model to ONNX, and I was wondering if you manage to get it to work? Would love to know how you achieved it!

hello,do you achieve it ?i want to save with torch.jit too?
