### ISSUE TITLE
Does this PsP support StyleGanV2-ADA with conditional labels dataset ?

### ISSUE THREAD

**Issue by thusinh1969** [eladrich/pixel2style2pixel#187]
Hi

Great work. Does this PsP support StyleGanV2-ADA with conditional labels dataset ? How do I structure my dataset for PsP training with conditional labels ?

Also, in order to use P2P effectively, is it correct that I have to:
1) Train my own StyleGanV2 first ? (and only StyleGanV2 without ADA/conditional label ?)
2) Re-train with p2p with exactly the same dataset / structure and pretrained model (1) above ?

Thanks for your explaination in advance.
Steve

**Comment by yuval-alaluf** [comment]
Hi @thusinh1969 
You are correct in your understanding of the steps: first you need to train StyleGAN2 on your domain. Then you freeze the generator and train the pSp encoder. 
We actually do support working with StyleGAN-ADA (since the architecture is exactly the same as StyleGAN2). Also note, that you can train pSp with a different dataset and structure that were used to train the generator.  For example, we use a FFHQ-trained generator but use CelebA-HQ in some of our experiments for training the encoder. 
One thing I did not understand is what you mean by conditional labels. Can you please clarify what you mean by this?

**Comment by dongyunkim-arch** [comment]
I think like traditional conditional GAN, styleGAN also supports conditional training, for example, training 0~9 mnist dataset with 0~9 labels., and then when generating images, we can use the label to create specific image (in this case, 0~9 number). I am also wondering if it is possible in p2p.
