### ISSUE TITLE
How to get realistic pictures from painting?

### ISSUE THREAD

**Issue by src-by-hannah** [eladrich/pixel2style2pixel#223]
Hello. Thanks for the wonderful project.

I came here after seeing this link. https://nerdist.com/article/artist-uses-ai-realistic-pictures-historical-figures/
I wanted to get the painting as a realistic photo like this, 
so I tried running colab, but the result was still disappointing.

![image](https://user-images.githubusercontent.com/69803444/143028337-33b44d3d-c4ec-44d0-b211-e80189d85d00.png)
This is the result I got. But still not satisfied.

And the result of the link is: 
![image](https://user-images.githubusercontent.com/69803444/143028313-990e0d43-6697-4044-9f1d-3b9a58375e80.png)
This is even more realistic than my results.

What do I need to do to get a picture like the link above?
Is it impossible to use only colab?

**Comment by yuval-alaluf** [comment]
If I am not mistaken, the person who created these images did some manual post-processing of the results. 
If you're not entirely satisfied with the results, you could also try working with e4e (encoder4editing) using the same approach as here. Since e4e encodes images closer to W, you may be able to get more realistic images.

**Comment by src-by-hannah** [comment]
It helped me a lot.
Thank you for answer :)
