### ISSUE TITLE
Running pSp without cuda?

### ISSUE THREAD

**Issue by manzke** [eladrich/pixel2style2pixel#244]
Is it possible to run pSp without the cuda parts implemented by nvidia? As far as I've understood, they are forbidding any commercial use, which means pSp has als no chance to be used for any real-life projects.
Even if you can request a license, you will get the answer that they are not planning to make it commercially available. :(

**Comment by yuval-alaluf** [comment]
I am not expert in licensing so I can't say what is and isn't allowed in terms of using NVIDIA's CUDA kernels for commercial use.  
Running pSp without cuda will be very difficult since inference time will be quite long.
You could try replacing the use of the CUDA kernels with a native implementation from rosinality: https://github.com/rosinality/stylegan2-pytorch/blob/master/op/upfirdn2d.py#L145
