### ISSUE TITLE
Toonify without a smile

### ISSUE THREAD

**Issue by mohammad-rj** [eladrich/pixel2style2pixel#248]
Thank you for the interesting work.

![image](https://user-images.githubusercontent.com/39571214/151279879-e2bcb5ca-41ef-4f49-8c71-86d0d0b6a597.png)

is it possible use toonify photo without smileing ?

![image](https://user-images.githubusercontent.com/39571214/151280321-0bb4fa76-aa04-49fe-8f98-58b2af02ca72.png)
I need the output like [this result](https://github.com/eladrich/pixel2style2pixel/issues/83#issue-805399229)

I'm not very familiar with these issues (StyleGAN - stylegan_weights - ffhq_cartoon_blended.pt - psp_ffhq_encode.pt - psp_ffhq_toonify.pt - stylegan2-ffhq-config-f.pkl - ffhq - training - models - dataset - res - targets - test and ... )
Is it possible for you guys make a colab for this particular purpose plz ?
or guide me how I can edit this [colab](https://colab.research.google.com/github/eladrich/pixel2style2pixel/blob/master/notebooks/inference_playground.ipynb) to do this ?

**Comment by yuval-alaluf** [comment]
The toonify StyleGAN generator has a bias for outputting images with a smile since that is the data it was trained on. 
What you can do is encode the image and then edit it to remove the smile. 
Although I don't have the time to make a notebook to demonstrate editing, there are a few scripts for a couple similar repos that may be able to help you out: 
1. https://github.com/omertov/encoder4editing/blob/main/editings/latent_editor.py 
Here the latent editor can get a `latent` representing the image encoding and a direction `smile` and you can edit the latent representation according to that direction. 
2. https://github.com/yuval-alaluf/restyle-encoder#editing
In another one of my repos, I provide more details and a script for performing editing on real images. Some changes are required, but this has 80% of what you need.
