### ISSUE TITLE
latent_avg is missing

### ISSUE THREAD

**Issue by CatDogS** [eladrich/pixel2style2pixel#271]
Thanks for your help!

I run `style2-pytorch` using my dataset. After getting the `.pt` file, I trained it in psp, but got the error.

`AttributeError: 'NoneType' object has no attribute 'repeat'`

![image](https://user-images.githubusercontent.com/43256810/167281259-092bc271-b89a-468e-84ef-c6651138323b.png)

Later I found out that the SG generator I trained in this `if statement` in the` psp.py` file does not have this parameter `latent_avg`.

![image](https://user-images.githubusercontent.com/43256810/167285643-b88f71ca-066d-4f79-8a7c-07bffacc9df0.png)

So I deleted what was mentioned in the error, and the code ran smoothly. I don't quite understand why.

I make `codes=codes`

![image](https://user-images.githubusercontent.com/43256810/167285803-799f717c-4370-4411-a7cf-87a3f2dddbbb.png)

to

![image](https://user-images.githubusercontent.com/43256810/167285921-a95c564a-fabb-4722-93ba-8b9c4628535a.png)

**Comment by yuval-alaluf** [comment]
The modification that you made is not exactly what you want if you set `start_from_latent_avg` to be `True`
If the `latent_avg` is missing from your `pt` file, you can estimate the `latent_avg`. 
This is actually already done in the code: 
https://github.com/eladrich/pixel2style2pixel/blob/334f45e43335e92822744849a546c82e1cc47bb3/training/coach.py#L39-L40
I am wondering why you still got the error since the above line should have solved the case where `latent_avg` is not in the `pt` file. 
When you ran the code, did you happen to see you entered the `if` above to estimate the latent average?
