### ISSUE TITLE
Use the pre-trained model for training

### ISSUE THREAD

**Issue by Leo1412** [eladrich/pixel2style2pixel#303]
Hi, thanks a lot for your contribution. I'm trying to perform some training using my own dataset based on the pre-trained super-resolution model. I've added the argument :--checkpoint_path = "path/to/pretrained_model". But it threw an error when I tried to start the training. Could you please explain why this happens? Thank you very much. (The error message is shown below)

<img width="1125" alt="Screenshot 2023-02-13 at 9 21 42 PM" src="https://user-images.githubusercontent.com/69981435/218469859-e9376e3d-6ceb-4fe2-a794-5f43f90d7ac6.png">

**Comment by yuval-alaluf** [comment]
This is because you are using a generator that outputs images at a resolution of 256x256. You can load the encoder and set `strict=False` when calling `torch.load()`. Note that since the generator is different, the pre-trained encoder may produce unexpected results. If you're fine-tuning then this could be fine, but the latent space is different, so you may be better off starting without a pre-trained pSp encoder.

**Comment by Leo1412** [comment]
> 

Thanks a lot!
