### ISSUE TITLE
Need help with running the code on CPU

### ISSUE THREAD

**Issue by SeulKi-S1K2** [eladrich/pixel2style2pixel#313]
I'm trying to run the code on CPU and I'm facing some issues. Can you please guide me on what changes I need to make to run the code on CPU?

**Comment by yuval-alaluf** [comment]
There are already numerous issues with this same questions so please refer to them. This is your best bet: https://github.com/eladrich/pixel2style2pixel/issues/18
As mentioned in the README, this code is designed to work with CUDA and we do not plan on supporting CPU-only. Unfortunately, I do not know what changes need to be made but will warn you that getting this to run on CPU can be a bit challenging because of StyleGAN's dependency on ninja.
