### ISSUE TITLE
How to train pSp on Z+ space?

### ISSUE THREAD

**Issue by RewindL** [eladrich/pixel2style2pixel#315]
Original pSp predict W+ latent that doesn't need to be projected by mlp layers from stylegan2. I am wondering if the encder can predict Z+ latent instead of W+ latent ? How should I modify the training code ?

**Comment by yuval-alaluf** [comment]
In order to operate in Z+ instead of W+ you'll need to dive into the [StyleGAN code](https://github.com/eladrich/pixel2style2pixel/blob/master/models/stylegan2/model.py) a bit. Basically, you'll want to take the output of the encoder and pass it to the Generator before the mapping network. Then, you'll want to apply the mapping network to the output of our encoder.
In order to determine how to do this, you'll need to dive into the code to understand where the mapping network happens and where the encoder outputs come into play.

**Comment by RewindL** [comment]
> In order to operate in Z+ instead of W+ you'll need to dive into the [StyleGAN code](https://github.com/eladrich/pixel2style2pixel/blob/master/models/stylegan2/model.py) a bit. Basically, you'll want to take the output of the encoder and pass it to the Generator before the mapping network. Then, you'll want to apply the mapping network to the output of our encoder. In order to determine how to do this, you'll need to dive into the code to understand where the mapping network happens and where the encoder outputs come into play.

I get the spirit. It works to add mlp projector before sending pSp style into StyleGAN2 generator. But results can't compete with W+ pSp model. The reason might be that projecting latent from Z+ to W+ using pretrained mlp layers might reduce effect of structure controlling ability. I'm still exploring a suitable Z+ latent training method, which support some editing method on Z+ space (that can't work on W+ because StyleGAN can't generate from any sampled latent from W+). Anyway, thanks for your reply.
