### ISSUE TITLE
Is it possible to create output images in profile (side-on) perspective using sketch to face?

### ISSUE THREAD

**Issue by EugenusRex** [eladrich/pixel2style2pixel#316]
![63d3ac9a7d5587 51032775-original](https://github.com/eladrich/pixel2style2pixel/assets/114542539/d7b307c6-2b1e-44a1-b50b-99fe8e3c5350)
![gettyimages-1312488275-2048x2048](https://github.com/eladrich/pixel2style2pixel/assets/114542539/f4ca4109-f101-463c-bcbf-b87a254620fe)
![out (3)](https://github.com/eladrich/pixel2style2pixel/assets/114542539/3ee9829a-7896-4fc1-a9c5-345714c55890)

I have been experimenting with applying the Celebs Sketch-to-Face model to the profiles of Kings found on Anglo-Saxon coins. As you can see, it is yielding some interesting results. That said, it would be desirable to have a profile/side-on view of the output image to demonstrate the transformation, in a complete sense. 

Is it possible to alter the model so that it gives an output in a profile/side-on view? Alternatively, could you suggest any other programme or website that could rotate the faces in the output images I already have by 90 degrees?

As stated in a previous post, I am a complete novice when it comes to coding and would appreciate any suggestions.

Thank you, kindly, in advance.

**Comment by yuval-alaluf** [comment]
The sketch-to-face model is trained on sketches extracted from CelebA-HQ, which are generally frontal images. Therefore, the generator won't really be able to create profile perspective image since the generator doesn't really know how to generate such faces. If you would want to do this, you'll need to train your own StyleGAN generator on these types of images.
