### ISSUE TITLE
Training for targets other than human faces?

### ISSUE THREAD

**Issue by lukesionkirax** [eladrich/pixel2style2pixel#37]
Is it possible to train psp for any domain or does it only work for human faces?

**Comment by yuval-alaluf** [comment]
Hi @lukesionkirax ,
Yes, pSp can be used on other domains. You would need to use a pretrained StyleGAN generator in the domain of interest instead of the FFHQ StyleGAN we used. Please note that some small adjustments may need to be made. For example, the generator defined in pSp is defined to output images of 1024: 
https://github.com/eladrich/pixel2style2pixel/blob/751fcbd9ffcb86487afdaa6a7e5953b94e28369f/models/psp.py#L28
Therefore, you may need to change this value according to the StyleGAN model you wish to use. 
In addition, the FFHQ StyleGAN uses 18 style vectors which may be different in other domains that output smaller images. Therefore, some other changes may be required.
