### ISSUE TITLE
Pausing for testing during training

### ISSUE THREAD

**Issue by spamfold3r** [eladrich/pixel2style2pixel#40]
Hi

I am in the process of retraining the encoder and was wondering what the procedure would be for testing the checkpoints as expectedly there isn't enough memory to train and test at the same time.

It's been training for roughly 2/3 days now. Would I pause training and test, or terminate training and test and then if desired restart training from the best checkpoint?

Are there flags for pausing etc?

Cheers!

**Comment by yuval-alaluf** [comment]
Hi. If I understand you correctly, calling `self.validate()` in Coach() results in out of memory?  
If that is the case, I wouldn't recommend pausing training or terminating and restarting because the current code does not keep the state of the optimizer.   
If you find that you are unable to run validation during training I would recommend setting the save interval to say `5000` and validation interval to the maximum number of steps you're training for. In doing so, you will not run validation during training, but save a checkpoint every 5000 intervals. After training, you have a bunch of checkpoints that you can validate using `inference.py` and our metrics scripts. 
(5000 was used an example, feel free to change depending on how often you think you should save checkpoints).

**Comment by spamfold3r** [comment]
I'm not sure whether this is the same thing as what you're saying, but I am trying to run `inference.py` in a different terminal instance whilst training is happening, which results in an error relating to insufficient CUDA memory. 

I'm just trying to test the checkpoints using `inference.py`, but am unsure of how to do this. I am using the recommended setting listed in the training section of the documentation.

**Comment by yuval-alaluf** [comment]
Ok that makes more sense. You (most likely) won't be able to run training and inference on the same gpu.     
Can I ask why you are running `inference.py` during training? During training we output logs on the training and test images showing the input, target, and output images during each validation interval. This should help you follow the training progress.

**Comment by spamfold3r** [comment]
Ahhhhhh I see, thank you. I was not aware of the visualizations throughout the training process, hence why I thought of running `inference.py`. My apologies.

As a newcomer, another question - at what point should training stop? Will it stop at a designated point or is it a matter of monitoring the scores and terminating when you see fit?

**Comment by yuval-alaluf** [comment]
All good.  
Regarding your question, by defaulting we run for 500,000 steps, but that is more than we used or you that you will probably need.  
We plot the training and test losses during training using tensorboard. I would recommend connecting to tensorboard to see when the model stops improving. When you see the model has converged (i.e. the test losses stop decreasing), you can stop training and use the best checkpoint obtained to perform inference. 
I hope that helps answer your question.

**Comment by spamfold3r** [comment]
Yes that's just what I was after! Once again, thank you for your help. 😎

**Comment by yuval-alaluf** [comment]
Happy to help!
