### ISSUE TITLE
About alignment

### ISSUE THREAD

**Issue by wty-ustc** [eladrich/pixel2style2pixel#48]
Thanks for your excellent work! I have read your code, and I find you don't use any alignment in training encoder for id_loss, so if I want to training on my own datasets, alignment should be done before training, right?

**Comment by yuval-alaluf** [comment]
Yes. For training the encoder the data should be aligned (we used FFHQ and CelebsA-HQ which are both pre-aligned). 
As for the `id_loss` not using alignment, we do an approximation for the alignment in order to crop the interesting face region before passing the images to the ArcFace network: 
https://github.com/eladrich/pixel2style2pixel/blob/ab147e9a759be0766c04da41b7ae807eeaabade3/criteria/id_loss.py#L16-L20

**Comment by wty-ustc** [comment]
So why do you use alignment in calc_id_loss_parallel.py when calculate the metrics.

**Comment by yuval-alaluf** [comment]
Notice that the alignment and cropping used for training StyleGAN with FFHQ uses dlib while for `calc_id_loss_parallel.py` we use MTCNN for alignment and cropping the images to 112x112 before passing the images to the CircularFace network.  
Each alignment is slightly different and is used for a different purpose.

**Comment by wty-ustc** [comment]
Thank you!
