### ISSUE TITLE
Decoding Images

### ISSUE THREAD

**Issue by yagizcolak** [eladrich/pixel2style2pixel#55]
Hello sir, I am using the images that I encoded using your repo to make a style mixing project. I am using stylegan2's run_generator.py file to do this. But when I load my encoded images, it is a lot different. I think I am using stylegan2's generator to decode the images. But the results are quite different than what I see here.

Left side is the original picture, right side is the encoded image using your repo
![appiahEncoded](https://user-images.githubusercontent.com/44118056/101830657-eb378a80-3b45-11eb-9f37-3cf9e0578bb1.png)

This is the decoded image
![appiahDecoded](https://user-images.githubusercontent.com/44118056/101830659-ebd02100-3b45-11eb-9b50-916b8d5a6823.PNG)

What do you think the reason can be?

**Comment by yuval-alaluf** [comment]
Hi, it seems like the reconstruction results with pSp seem quite good. As this seems to be an issue related to the `run_generator.py` script of the official StyleGAN2 repo, I would recommend asking on their repository since we are not too familiar with the inner workings of the tensorflow code.  

In any case, please note that we add support for style mixing in this code. This could save you the need for converting between our Pytorch code/models and their tensorflow code/models.

**Comment by yuval-alaluf** [comment]
The inference notebook provides an example for style mixing for segmentation to image and sketch to image, but can easily be extended for the other applications. 
Further, we provide a style mixing script with an example usage in the README:
https://github.com/eladrich/pixel2style2pixel#multi-modal-synthesis-with-style-mixing
