### ISSUE TITLE
Can I perform operations on image latent_directions using your model's API

### ISSUE THREAD

**Issue by Vova-B** [eladrich/pixel2style2pixel#69]
I want to change the age or gender in the photo, I get latent_directions for the picture and would like to make these changes immediately, I have the calculated files for this from other examples, what operations do I need to do to solve this problem using only your API?

**Comment by yuval-alaluf** [comment]
It sounds like you want to save the latent code for each input image. There are a few small changes you need to make in order to do this. I explain exactly how in Issue #36 so have a look there.

Once you have these latent codes, you can play around in the latent space using the latent direction of StyleGAN2 models. While we don't provide code for latent space traversal in this repo, it seems like you already have the directions you want. Just make sure that the latent directions you have are for StyleGAN2 models.

**Comment by Vova-B** [comment]
@yuval-alaluf yes, I already saved the latent code for each input image and i already have directions for `SryleGan2` model. How can I use them to make changes to the input image using your code. That is, I have latent_direction for my input image it, s shape `[18, 512]` and latent direction for StyleGan2 model, for example `age.npy [18, 512]`, also I have `coeffs` for transformation, how can I use this in your model?

**Comment by yuval-alaluf** [comment]
We do not support latent space manipulation with our code. There should be other works that specialize in latent space traversal with published implementation.

**Comment by Vova-B** [comment]
Problem solved, I was able to modify your code to work with latent space

**Comment by federicoromeo** [comment]
> Problem solved, I was able to modify your code to work with latent space

I'm actually doing the same thing, can you help me out?
