### ISSUE TITLE
Why using start_from_latent_avg to normalize d_latent?

### ISSUE THREAD

**Issue by ChengBinJin** [eladrich/pixel2style2pixel#70]
I just curious about why using latent_avg to normalize d_latent?
The performance will be worse if we setting the start_from_latent_avg flag to False to train the encoder?
I think StyleGAN-Tensorflow didn't use this kind of normalization, right?

codes = self.encoder(x)
# normalize with respect to the center of an average face
if self.opts.start_from_latent_avg:
    if self.opts.learn_in_w:
        codes = codes + self.latent_avg.repeat(codes.shape[0], 1)
    else:
	codes = codes + self.latent_avg.repeat(codes.shape[0], 1, 1)
```

**Comment by yuval-alaluf** [comment]
We found that starting from the average latent code provided better initialization for training. By starting from the latent average, the encoder learns to generate latent codes with respect to this latent average instead of from the zero latent code. We find that this provides better results compared to training with respect to the zero latent code.

**Comment by ChengBinJin** [comment]
@yuval-alaluf 
I see, thank you for your kindly reply! I will close this issue.
