### ISSUE TITLE
importing ffhq encoder into onnx fromat 

### ISSUE THREAD

**Issue by levindabhi** [eladrich/pixel2style2pixel#72]
I am trying to convert pSp module of ffhq encoder into onnx format, but I am encountering error of
 `RuntimeError: ONNX export failed: Couldn't export Python operator FusedLeakyReLUFunction`
- PyTorch version: 1.7.0+cu101
- opset_version: 11

**Comment by yuval-alaluf** [comment]
Hi, we are not too familiar with converting models using ONNX. If I had to guess, the reason you are encounter the issue is due to the custom cuda extensions that StyleGAN uses (they can be found in the `models/stylegan2/op` directory).  
Your best bet is to open an issue with ONNX and maybe someone more familiar with its inner workings can assist you.
