### ISSUE TITLE
question regarding learn_in_w

### ISSUE THREAD

**Issue by jays0606** [eladrich/pixel2style2pixel#81]
There's an argument --learn_in_w in train_options, which says learn in w space instead of w+. 

Best to my knowledge, stylegan2 generates a random vector w of shape (,512), which passes through the mapping network, and generates a vector w+ of shape (18,512) to generate images through the generator. 

In pSp, the psp encoder learns to generate the w+ vector by training on paired data. So, when I input an image through the psp encoder, it returns the w+ vector. 

My question is, by setting learn_in_w as true, will I be able extract w instead of w+ ? If true, will I be able to generate similar results by passing on w to the generator? 

Thank you very much for your work.

**Comment by yuval-alaluf** [comment]
> My question is, by setting learn_in_w as true, will I be able extract w instead of w+ ?

Correct, you can use the flag `--learn_in_w` for training an encoder into W instead of W+. Note that when we set `learn_in_w` to true, we also set the encoder type equal to `BackboneEncoderUsingLastLayerIntoW` in order to output a single w vector instead of 18 different vectors.  

> will I be able to generate similar results by passing on w to the generator?

In our paper, we provided an ablation study showing the benefit of using our FPN encoder into W+ compared to an encoder tasked with encoding a single w vector. There we showed that the FPN achieves superior performance compared to the W encoder.

**Comment by jays0606** [comment]
Okay Thank you very much! The code is working well. 

One more thing, I failed to find a pretrained model for the ir-se 152. By any chance, do you have a checkpoint available for ir-se 100 or 152? 

Again, Thank you very much

**Comment by yuval-alaluf** [comment]
We got our pretrained model from https://github.com/TreB1eN/InsightFace_Pytorch
You can check if the repo contains other pretrained models.

**Comment by jays0606** [comment]
I’ll check the repo.

Thank you very much!

2021년 2월 8일 (월) 오후 4:14, yuval-alaluf <notifications@github.com>님이 작성:
