### ISSUE TITLE
Output seems a bit faded

### ISSUE THREAD

**Issue by cvmlddev** [eladrich/pixel2style2pixel#85]
Hi,
I trained the toonification model with a good quality paired dataset. The output looks good, as in, the eyes are big, Looks like a cartoon for sure.
But it seems to be a bit faded.
Trained with default hyper parameters, Changing them does not seem to have a huge impact
`lpips_lambda=0.8 , l2_lambda=1, id_lambda=1 , w_norm_lambda=0.025 ,stylegan_weights =pretrained_models/ffhq_cartoon_blended.pt
`

Attaching a sample output below
![faded](https://user-images.githubusercontent.com/78845460/108984300-c323e600-76b5-11eb-8480-cc71623b0fff.jpeg)

**Comment by yuval-alaluf** [comment]
Based on your earlier issue ( #83 ), the "fading" effect your seeing isn't related to your loss lambdas since previously you were able to get more "colorful" results. Therefore, I think the fading is due to some other factor such as the paired data used for this training compared to the paired data used before.  

P.S. I personally like your previous results more than the example you posted here, but both results look good :)
